export const SEARCH_ASTEROID_START = 'SEARCH_ASTEROID_START';
export const SEARCH_ASTEROID_SUCCESS = 'SEARCH_ASTEROID_SUCCESS';
export const SEARCH_ASTEROID_FAIL = 'SEARCH_ASTEROID_FAIL';
export const GET_ALL_ASTEROIDS_START = 'GET_ALL_ASTEROIDS_START';
export const GET_ALL_ASTEROIDS_SUCCESS = 'GET_ALL_ASTEROIDS_SUCCESS';
export const GET_ALL_ASTEROIDS_FAIL = 'GET_ALL_ASTEROIDS_FAIL';
